### ISSUE TITLE
Failed at first run

### ISSUE THREAD

**Issue by chrisiek** [hiattp/express3-mongodb-bootstrap-demo#2]
After installing all files I run the application and got an error like this:

I'm am new to node.js and perhaps it is a simple problem but I can't cope with it. I use Win XP now.

<pre><code>
C:\work2\express3-mongodb-bootstrap-demo-master>node app.js

C:\work2\express3-mongodb-bootstrap-demo-master\node_modules\bcrypt\node_modules
\bindings\bindings.js:79
        throw e
              ^
Error: no errorC:\work2\express3-mongodb-bootstrap-demo-master\node_modules\bcry
pt\build\Release\bcrypt_lib.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (C:\work2\express3-mongodb-bootstrap-demo-master\node_modules\bc
rypt\node_modules\bindings\bindings.js:74:15)
    at Object.<anonymous> (C:\work2\express3-mongodb-bootstrap-demo-master\node_
modules\bcrypt\bcrypt.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

C:\work2\express3-mongodb-bootstrap-demo-master>npm ls
application-name@0.0.1 C:\work2\express3-mongodb-bootstrap-demo-master
+¦T bcrypt@0.7.5
- L¦¦ bindings@1.0.0
+¦¦ connect-flash@0.1.0
+¦¦ ejs@0.8.3
+¦¦ ejs-locals@1.0.2
+¦T express@3.1.1
- +¦¦ buffer-crc32@0.2.1
- +¦¦ commander@0.6.1
- +¦T connect@2.7.4
- - +¦¦ buffer-crc32@0.1.1
- - +¦¦ bytes@0.2.0
- - +¦¦ formidable@1.0.11
- - +¦¦ pause@0.0.1
- - L¦¦ qs@0.5.1
- +¦¦ cookie@0.0.5
- +¦¦ cookie-signature@0.0.1
- +¦¦ debug@0.7.2
- +¦¦ fresh@0.1.0
- +¦¦ methods@0.0.1
- +¦¦ mkdirp@0.3.5
- +¦¦ range-parser@0.0.4
- L¦T send@0.1.0
-   L¦¦ mime@1.2.6
+¦T express-mailer@0.2.0
- L¦T nodemailer@0.3.44
-   +¦T mailcomposer@0.1.31
-   - +¦¦ mime@1.2.9
-   - L¦T mimelib@0.2.12
-   -   +¦¦ addressparser@0.1.3
-   -   L¦T encoding@0.1.6
-   -     L¦¦ iconv-lite@0.2.7
-   +¦T optimist@0.4.0
-   - L¦¦ wordwrap@0.0.2
-   L¦T simplesmtp@0.2.4
-     +¦¦ rai@0.1.7
-     L¦¦ xoauth2@0.1.7
+¦T express-validator@0.3.2
- L¦¦ validator@0.4.25
+¦T mongoose@3.6.4
- +¦¦ hooks@0.2.1
- +¦T mongodb@1.2.14
- - L¦¦ bson@0.1.8
- +¦¦ mpath@0.1.1
- +¦T mpromise@0.2.1
- - L¦¦ sliced@0.0.4
- +¦¦ ms@0.1.0
- +¦¦ muri@0.3.1
- L¦¦ sliced@0.0.3
+¦T passport@0.1.16
- L¦¦ pkginfo@0.2.3
L¦T passport-local@0.1.6
  L¦¦ pkginfo@0.2.3
</code></pre>

**Comment by hiattp** [comment]
This might be related to #1, have you tried `npm install bcrypt`?
