### ISSUE TITLE
sudo npm install bcrypt gives error

### ISSUE THREAD

**Issue by krishnashetty0** [hiattp/express3-mongodb-bootstrap-demo#5]
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.7 install /home/krishna/test/express3-mongodb-bootstrap-demo/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:152:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:95:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:694:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at maybeClose (child_process.js:808:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1025:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Pipe.close (net.js:459:12)
gyp ERR! System Linux 3.8.0-33-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/krishna/test/express3-mongodb-bootstrap-demo/node_modules/bcrypt
gyp ERR! node -v v0.11.10-pre
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-33-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! cwd /home/krishna/test/express3-mongodb-bootstrap-demo
npm ERR! node -v v0.11.10-pre
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/krishna/test/express3-mongodb-bootstrap-demo/npm-debug.log
npm ERR! not ok code 0

**Comment by hiattp** [comment]
Please follow the instructions [here](https://github.com/ncb000gt/node.bcrypt.js) to make sure you can install bcrypt normally. This is a dependency (and a fairly popular one), so you'll want to trouble-shoot it independently of this boiler plate code.
